"""added the coaches table

Revision ID: a9ecbb954437
Revises: 20a4ba2d5981
Create Date: 2024-04-17 12:34:21.393265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ecbb954437'
down_revision = '20a4ba2d5981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('years_coached', sa.Integer(), nullable=True),
    sa.Column('teams_coached', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coaches')
    # ### end Alembic commands ###
